#!/bin/sh

PYTHON=python3.1
PYTHON_CONFIG=python3.1-config

# PYTHON_FLAGS="-I/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -I/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386"
PYTHON_FLAGS=`$PYTHON_CONFIG --cflags`
